services:
  search-featured-results:
    environment:
      # App's editor group, 'App-MWS-featured-search' is not setup in QUAL AD at this time.
      EDITOR_GROUP_NAME: '$$staff-current'
      # JWT_SECRET: <pull-from-ansible or f-s-r-secrets file as FEATURED_SECRET>
      # When using real auth update the unified-auth url to the corresponding landscape's hostname and set the s-f-r secret to the above JWT_SECRET value.
      JWT_TRUSTED_ISSUERS: '[{ "iss": "unified-auth", "url": "http://fakeauth/jwks" }, { "iss": "search-featured-results", "secret": "localtoken" }]'
      MOTION_TOKEN: <pull-from-ansible>
      MYSQL_PASS: secret
      PUBLIC_AUTH_BASE_URL: http://localhost:3001
      # Below is optional and defaults to 'search-featured-results' if not defined in environment.
      # PUBLIC_AUTH_CLIENT_ID: search-featured-results
      WAREHOUSE_PASS: <pull-from-ansible>
  search-featured-results-cron:
    environment:
      # Toggle the MOTION_TOKEN with comments to enable being able to hit Motion with the heavy people query any time you need to
      # get fresh people results added to your local volume's test data.
      # Otherwise ---- Leave it commented out to be considerate to Motion.
      # MOTION_TOKEN: <pull-from-ansible>
      MYSQL_PASS: secret
  mysql:
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh" ,"--innodb_initialized"]
      start_period: 4s
  mongodb:
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      start_period: 4s
networks:
  default:
    external:
      name: txst-tunnel_default
