version: '3'
services:
  search-featured-results:
    build:
      context: .
      dockerfile: Dockerfile.dev
    read_only: true
    environment:
      DB_HOST: mongodb
      NODE_ENV: development
      FEATURED_SECRET: mysecret
      MOTION_URL: https://motion.tr.qual.txstate.edu/v2/api
      MOTION_TOKEN: set this in docker-compose.override.yml
      #MYSQL_HOST: itsdbqa-mysql.its.qual.txstate.edu
      #MYSQL_DATABASE: peoplesearch
      #MYSQL_PORT: 3307
      #MYSQL_USER: peoplesearch
      #MYSQL_PASS: set in docker-compose.override.yml
      MYSQL_HOST: mysql
      MYSQL_DATABASE: peoplesearch
      MYSQL_PORT: 3306
      MYSQL_PASS: secret
      MYSQL_SKIPTZFIX: 'true'
      WAREHOUSE_HOST: phrixos2.its.txstate.edu
      WAREHOUSE_PORT: 3306
      WAREHOUSE_USER: dbread
      WAREHOUSE_PASS: set in docker-compose.override.yml
      WAREHOUSE_DATABASE: peoplesearch
    volumes:
      - ./lib:/usr/src/app/lib
      - ./models:/usr/src/app/models
      - ./index.js:/usr/src/app/index.js
    ports:
      - 80:80
    depends_on:
      - mongodb
      - mysql
  mysql:
    # Switched to using local instance of mysql for development so we can
    # docker-compose down -v to reset when we want to rebuild a table.
    image: percona:5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: peoplesearch
    ports:
      - 3306:3306
    volumes:
      - peoplesearchdata:/var/lib/mysql
  mongodb:
    image: mongo:latest
    command: --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - featureddb:/data/db
volumes:
  featureddb: {}
  peoplesearchdata: {}
