version: '3'
services:
  search-featured-results:
    build:
      context: .
      dockerfile: Dockerfile.dev
    read_only: true
    environment:
      DB_HOST: mongodb
      NODE_ENV: development
      FEATURED_SECRET: mysecret
      #MYSQL_HOST: phrixos2.its.txstate.edu
      MYSQL_HOST: itsdbqa-mysql.its.qual.txstate.edu
      #MYSQL_HOST: 0.0.0.0
      MYSQL_DATABASE: peoplesearch
      MYSQL_PORT: 3307
      #MYSQL_USER: dbread
      MYSQL_USER: peoplesearch
      MYSQL_PASS: set in docker-compose.override.yml
      MYSQL_SKIPTZFIX: 'true'
    volumes:
      - ./lib:/usr/src/app/lib
      - ./models:/usr/src/app/models
      - ./index.js:/usr/src/app/index.js
    ports:
      - 80:80
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    command: --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - featureddb:/data/db
volumes:
  featureddb: {}
