version: '3'
services:
  search-featured-results-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      API_HOST: search-featured-results
      DB_HOST: mongodb
      FEATURED_SECRET: mysecret
    links:
      - search-featured-results
      - mongodb
  search-featured-results:
    build: .
    read_only: true
    environment:
      DB_HOST: mongodb
      FEATURED_SECRET: mysecret
      MOTION_URL: https://motion.tr.qual.txstate.edu/v2/graphql
      MOTION_TOKEN: set this in docker-compose.override.yml
      MYSQL_HOST: mysql
      MYSQL_DATABASE: peoplesearch
      MYSQL_PASS: secret
    depends_on:
      - mongodb
      - mysql
  mongodb:
    image: mongo:latest
  mysql:
    # Switched to using local instance of mysql for development so we can
    # docker-compose down -v to reset when we want to rebuild a table.
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: peoplesearch
    ports:
      - 3306:3306
    volumes:
      - peoplesearchdata:/var/lib/mysql
volumes:
  peoplesearchdata: {}
