version: '3'
services:
  search-featured-results:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: mongodb
      NODE_ENV: development
      FEATURED_SECRET: mysecret
      MOTION_URL: https://motion.tr.qual.txstate.edu/v2/api
      MOTION_TOKEN: set this in docker-compose.override.yml
      MYSQL_HOST: mysql
      MYSQL_DATABASE: peoplesearch
      MYSQL_PORT: 3306
      MYSQL_PASS: secret
    volumes:
      - ./src:/usr/app/src
    ports:
      - 80:80
    depends_on:
      - mongodb
      - mysql
  mysql:
    # Switched to using local instance of mysql for development so we can
    # docker-compose down -v to reset when we want to rebuild a table.
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: peoplesearch
    ports:
      - 3306:3306
    volumes:
      - peoplesearchdata:/var/lib/mysql
  mongodb:
    image: mongo:latest
    command: --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - featureddb:/data/db
volumes:
  featureddb: {}
  peoplesearchdata: {}
