version: '3'
services:
  search-featured-results-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      API_HOST: search-featured-results
      DB_HOST: mongodb
      FEATURED_SECRET: mysecret
    links:
      - search-featured-results
      - mongodb
  search-featured-results:
    build: .
    read_only: true
    environment:
      DB_HOST: mongodb
      FEATURED_SECRET: mysecret
      MOTION_URL: https://motion.tr.qual.txstate.edu/v2/graphql
      MOTION_TOKEN: set this in docker-compose.override.yml
      #MYSQL_HOST: phrixos2.its.txstate.edu
      #MYSQL_HOST: itsdbqa-mysql.its.qual.txstate.edu
      #MYSQL_HOST: 0.0.0.0
      #MYSQL_DATABASE: peoplesearch
      #MYSQL_PORT: 3307
      #MYSQL_USER: dbread
      #MYSQL_USER: peoplesearch
      #MYSQL_PASS: set in docker-compose.override.yml
      MYSQL_SKIPTZFIX: 'true'
      MYSQL_HOST: mysql
      MYSQL_DATABASE: peoplesearch
      MYSQL_PASS: secret
      WAREHOUSE_HOST: phrixos2.its.txstate.edu
      WAREHOUSE_USER: dbread
      WAREHOUSE_PASS:
      WAREHOUSE_DATABASE: peoplesearch
    depends_on:
      - mongodb
      - mysql
  mongodb:
    image: mongo:latest
    command: --logpath /dev/null
  mysql:
    # Switched to using local instance of mysql for development so we can
    # docker-compose down -v to reset when we want to rebuild a table.
    image: percona:5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: peoplesearch
    ports:
      - 3306:3306
    volumes:
      - peoplesearchdata:/var/lib/mysql
volumes:
  peoplesearchdata: {}
