version: '3'
services:
  search-featured-results:
    build: .
    environment:
      DB_HOST: mongodb
      NODE_ENV: development
      FEATURED_SECRET: mysecret
    ports:
      - 443:443
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    command: --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - featureddb:/data/db
volumes:
  featureddb: {}
