version: '3'
services:
  search-featured-results-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      API_HOST: search-featured-results
      DB_HOST: mongodb
      FEATURED_SECRET: mysecret
    links:
      - search-featured-results
      - mongodb
  search-featured-results:
    build: .
    read_only: true
    environment:
      DB_HOST: mongodb
      FEATURED_SECRET: mysecret
      MYSQL_HOST: phrixos2.its.txstate.edu
      MYSQL_DATABASE: peoplesearch
      MYSQL_USER: dbread
      MYSQL_PASS: set in docker-compose.override.yml
      MYSQL_SKIPTZFIX: 'true'
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    command: --logpath /dev/null